// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invertorymanagement.proto

package grpc.services.inventorymanagement;

public interface ItemRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventorymanagement.ItemRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the item to check stock info and item info
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  java.lang.String getItemId();
  /**
   * <pre>
   * ID of the item to check stock info and item info
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();
}
