// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invertorymanagement.proto

package grpc.services.inventorymanagement;

public interface ItemInfoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventorymanagement.ItemInfo)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the item
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  java.lang.String getItemId();
  /**
   * <pre>
   * ID of the item
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <pre>
   * Name of the item
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * Name of the item
   * </pre>
   *
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * Description of the item
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  java.lang.String getDescription();
  /**
   * <pre>
   * Description of the item
   * </pre>
   *
   * <code>string description = 3;</code>
   */
  com.google.protobuf.ByteString
      getDescriptionBytes();

  /**
   * <pre>
   * Price of the item
   * </pre>
   *
   * <code>float price = 4;</code>
   */
  float getPrice();
}
