// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invertorymanagement.proto

package grpc.services.inventorymanagement;

public interface StatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventorymanagement.Status)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status message
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Status message
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Success flag
   * </pre>
   *
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
