// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: invertorymanagement.proto

package grpc.services.inventorymanagement;

public interface UpdateRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:inventorymanagement.UpdateRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the item
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  java.lang.String getItemId();
  /**
   * <pre>
   * ID of the item
   * </pre>
   *
   * <code>string item_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getItemIdBytes();

  /**
   * <pre>
   * Quantity change (+/-)
   * </pre>
   *
   * <code>int32 quantity = 2;</code>
   */
  int getQuantity();
}
