// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

public interface ApplyVoucherOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.ApplyVoucher)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the cart 
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  java.lang.String getCartId();
  /**
   * <pre>
   * ID of the cart 
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCartIdBytes();

  /**
   * <pre>
   * Voucher code
   * </pre>
   *
   * <code>string voucher_code = 2;</code>
   */
  java.lang.String getVoucherCode();
  /**
   * <pre>
   * Voucher code
   * </pre>
   *
   * <code>string voucher_code = 2;</code>
   */
  com.google.protobuf.ByteString
      getVoucherCodeBytes();
}
