// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

public interface CartContentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.CartContents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .checkout.CartItem items = 1;</code>
   */
  java.util.List<grpc.services.checkout.CartItem> 
      getItemsList();
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .checkout.CartItem items = 1;</code>
   */
  grpc.services.checkout.CartItem getItems(int index);
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .checkout.CartItem items = 1;</code>
   */
  int getItemsCount();
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .checkout.CartItem items = 1;</code>
   */
  java.util.List<? extends grpc.services.checkout.CartItemOrBuilder> 
      getItemsOrBuilderList();
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .checkout.CartItem items = 1;</code>
   */
  grpc.services.checkout.CartItemOrBuilder getItemsOrBuilder(
      int index);

  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  java.lang.String getCartId();
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCartIdBytes();

  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 3;</code>
   */
  float getTotal();
}
