// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

public interface CheckoutContentsOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.CheckoutContents)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  boolean hasItem();
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  grpc.services.checkout.CheckoutItem getItem();
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  grpc.services.checkout.CheckoutItemOrBuilder getItemOrBuilder();

  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  java.lang.String getCartId();
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  com.google.protobuf.ByteString
      getCartIdBytes();

  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 3;</code>
   */
  float getTotal();
}
