// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

/**
 * <pre>
 * The response message containing the list of items and total price in the checkout.
 * </pre>
 *
 * Protobuf type {@code checkout.CheckoutContents}
 */
public  final class CheckoutContents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:checkout.CheckoutContents)
    CheckoutContentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CheckoutContents.newBuilder() to construct.
  private CheckoutContents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CheckoutContents() {
    cartId_ = "";
    total_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CheckoutContents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            grpc.services.checkout.CheckoutItem.Builder subBuilder = null;
            if (item_ != null) {
              subBuilder = item_.toBuilder();
            }
            item_ = input.readMessage(grpc.services.checkout.CheckoutItem.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(item_);
              item_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cartId_ = s;
            break;
          }
          case 29: {

            total_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_CheckoutContents_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_CheckoutContents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.checkout.CheckoutContents.class, grpc.services.checkout.CheckoutContents.Builder.class);
  }

  public static final int ITEM_FIELD_NUMBER = 1;
  private grpc.services.checkout.CheckoutItem item_;
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  public boolean hasItem() {
    return item_ != null;
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  public grpc.services.checkout.CheckoutItem getItem() {
    return item_ == null ? grpc.services.checkout.CheckoutItem.getDefaultInstance() : item_;
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>.checkout.CheckoutItem item = 1;</code>
   */
  public grpc.services.checkout.CheckoutItemOrBuilder getItemOrBuilder() {
    return getItem();
  }

  public static final int CART_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object cartId_;
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  public java.lang.String getCartId() {
    java.lang.Object ref = cartId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cartId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCartIdBytes() {
    java.lang.Object ref = cartId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cartId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 3;
  private float total_;
  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 3;</code>
   */
  public float getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (item_ != null) {
      output.writeMessage(1, getItem());
    }
    if (!getCartIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cartId_);
    }
    if (total_ != 0F) {
      output.writeFloat(3, total_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (item_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getItem());
    }
    if (!getCartIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cartId_);
    }
    if (total_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.checkout.CheckoutContents)) {
      return super.equals(obj);
    }
    grpc.services.checkout.CheckoutContents other = (grpc.services.checkout.CheckoutContents) obj;

    boolean result = true;
    result = result && (hasItem() == other.hasItem());
    if (hasItem()) {
      result = result && getItem()
          .equals(other.getItem());
    }
    result = result && getCartId()
        .equals(other.getCartId());
    result = result && (
        java.lang.Float.floatToIntBits(getTotal())
        == java.lang.Float.floatToIntBits(
            other.getTotal()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasItem()) {
      hash = (37 * hash) + ITEM_FIELD_NUMBER;
      hash = (53 * hash) + getItem().hashCode();
    }
    hash = (37 * hash) + CART_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCartId().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTotal());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.checkout.CheckoutContents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.checkout.CheckoutContents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.CheckoutContents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.CheckoutContents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.checkout.CheckoutContents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the list of items and total price in the checkout.
   * </pre>
   *
   * Protobuf type {@code checkout.CheckoutContents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:checkout.CheckoutContents)
      grpc.services.checkout.CheckoutContentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_CheckoutContents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_CheckoutContents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.checkout.CheckoutContents.class, grpc.services.checkout.CheckoutContents.Builder.class);
    }

    // Construct using grpc.services.checkout.CheckoutContents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemBuilder_ == null) {
        item_ = null;
      } else {
        item_ = null;
        itemBuilder_ = null;
      }
      cartId_ = "";

      total_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_CheckoutContents_descriptor;
    }

    @java.lang.Override
    public grpc.services.checkout.CheckoutContents getDefaultInstanceForType() {
      return grpc.services.checkout.CheckoutContents.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.checkout.CheckoutContents build() {
      grpc.services.checkout.CheckoutContents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.checkout.CheckoutContents buildPartial() {
      grpc.services.checkout.CheckoutContents result = new grpc.services.checkout.CheckoutContents(this);
      if (itemBuilder_ == null) {
        result.item_ = item_;
      } else {
        result.item_ = itemBuilder_.build();
      }
      result.cartId_ = cartId_;
      result.total_ = total_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.checkout.CheckoutContents) {
        return mergeFrom((grpc.services.checkout.CheckoutContents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.checkout.CheckoutContents other) {
      if (other == grpc.services.checkout.CheckoutContents.getDefaultInstance()) return this;
      if (other.hasItem()) {
        mergeItem(other.getItem());
      }
      if (!other.getCartId().isEmpty()) {
        cartId_ = other.cartId_;
        onChanged();
      }
      if (other.getTotal() != 0F) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.checkout.CheckoutContents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.checkout.CheckoutContents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private grpc.services.checkout.CheckoutItem item_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder> itemBuilder_;
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public boolean hasItem() {
      return itemBuilder_ != null || item_ != null;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public grpc.services.checkout.CheckoutItem getItem() {
      if (itemBuilder_ == null) {
        return item_ == null ? grpc.services.checkout.CheckoutItem.getDefaultInstance() : item_;
      } else {
        return itemBuilder_.getMessage();
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public Builder setItem(grpc.services.checkout.CheckoutItem value) {
      if (itemBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        item_ = value;
        onChanged();
      } else {
        itemBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public Builder setItem(
        grpc.services.checkout.CheckoutItem.Builder builderForValue) {
      if (itemBuilder_ == null) {
        item_ = builderForValue.build();
        onChanged();
      } else {
        itemBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public Builder mergeItem(grpc.services.checkout.CheckoutItem value) {
      if (itemBuilder_ == null) {
        if (item_ != null) {
          item_ =
            grpc.services.checkout.CheckoutItem.newBuilder(item_).mergeFrom(value).buildPartial();
        } else {
          item_ = value;
        }
        onChanged();
      } else {
        itemBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public Builder clearItem() {
      if (itemBuilder_ == null) {
        item_ = null;
        onChanged();
      } else {
        item_ = null;
        itemBuilder_ = null;
      }

      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public grpc.services.checkout.CheckoutItem.Builder getItemBuilder() {
      
      onChanged();
      return getItemFieldBuilder().getBuilder();
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    public grpc.services.checkout.CheckoutItemOrBuilder getItemOrBuilder() {
      if (itemBuilder_ != null) {
        return itemBuilder_.getMessageOrBuilder();
      } else {
        return item_ == null ?
            grpc.services.checkout.CheckoutItem.getDefaultInstance() : item_;
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>.checkout.CheckoutItem item = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder> 
        getItemFieldBuilder() {
      if (itemBuilder_ == null) {
        itemBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder>(
                getItem(),
                getParentForChildren(),
                isClean());
        item_ = null;
      }
      return itemBuilder_;
    }

    private java.lang.Object cartId_ = "";
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public java.lang.String getCartId() {
      java.lang.Object ref = cartId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cartId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCartIdBytes() {
      java.lang.Object ref = cartId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cartId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder setCartId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder clearCartId() {
      
      cartId_ = getDefaultInstance().getCartId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder setCartIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartId_ = value;
      onChanged();
      return this;
    }

    private float total_ ;
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public float getTotal() {
      return total_;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public Builder setTotal(float value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:checkout.CheckoutContents)
  }

  // @@protoc_insertion_point(class_scope:checkout.CheckoutContents)
  private static final grpc.services.checkout.CheckoutContents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.checkout.CheckoutContents();
  }

  public static grpc.services.checkout.CheckoutContents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CheckoutContents>
      PARSER = new com.google.protobuf.AbstractParser<CheckoutContents>() {
    @java.lang.Override
    public CheckoutContents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CheckoutContents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CheckoutContents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CheckoutContents> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.checkout.CheckoutContents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

