// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

public interface ReceiptOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.Receipt)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the transaction
   * </pre>
   *
   * <code>string transaction_id = 1;</code>
   */
  java.lang.String getTransactionId();
  /**
   * <pre>
   * ID of the transaction
   * </pre>
   *
   * <code>string transaction_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getTransactionIdBytes();

  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 2;</code>
   */
  float getTotal();

  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CartItem purchased_items = 3;</code>
   */
  java.util.List<grpc.services.checkout.CartItem> 
      getPurchasedItemsList();
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CartItem purchased_items = 3;</code>
   */
  grpc.services.checkout.CartItem getPurchasedItems(int index);
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CartItem purchased_items = 3;</code>
   */
  int getPurchasedItemsCount();
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CartItem purchased_items = 3;</code>
   */
  java.util.List<? extends grpc.services.checkout.CartItemOrBuilder> 
      getPurchasedItemsOrBuilderList();
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CartItem purchased_items = 3;</code>
   */
  grpc.services.checkout.CartItemOrBuilder getPurchasedItemsOrBuilder(
      int index);
}
