// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

/**
 * Protobuf type {@code checkout.Receipt}
 */
public  final class Receipt extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:checkout.Receipt)
    ReceiptOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Receipt.newBuilder() to construct.
  private Receipt(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Receipt() {
    transactionId_ = "";
    total_ = 0F;
    purchasedItems_ = java.util.Collections.emptyList();
    message_ = "";
    success_ = false;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Receipt(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            transactionId_ = s;
            break;
          }
          case 21: {

            total_ = input.readFloat();
            break;
          }
          case 26: {
            if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
              purchasedItems_ = new java.util.ArrayList<grpc.services.checkout.CheckoutItem>();
              mutable_bitField0_ |= 0x00000004;
            }
            purchasedItems_.add(
                input.readMessage(grpc.services.checkout.CheckoutItem.parser(), extensionRegistry));
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            message_ = s;
            break;
          }
          case 40: {

            success_ = input.readBool();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
        purchasedItems_ = java.util.Collections.unmodifiableList(purchasedItems_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_Receipt_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_Receipt_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.checkout.Receipt.class, grpc.services.checkout.Receipt.Builder.class);
  }

  private int bitField0_;
  public static final int TRANSACTION_ID_FIELD_NUMBER = 1;
  private volatile java.lang.Object transactionId_;
  /**
   * <pre>
   * ID of the transaction
   * </pre>
   *
   * <code>string transaction_id = 1;</code>
   */
  public java.lang.String getTransactionId() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      transactionId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the transaction
   * </pre>
   *
   * <code>string transaction_id = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTransactionIdBytes() {
    java.lang.Object ref = transactionId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      transactionId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 2;
  private float total_;
  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 2;</code>
   */
  public float getTotal() {
    return total_;
  }

  public static final int PURCHASED_ITEMS_FIELD_NUMBER = 3;
  private java.util.List<grpc.services.checkout.CheckoutItem> purchasedItems_;
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
   */
  public java.util.List<grpc.services.checkout.CheckoutItem> getPurchasedItemsList() {
    return purchasedItems_;
  }
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
   */
  public java.util.List<? extends grpc.services.checkout.CheckoutItemOrBuilder> 
      getPurchasedItemsOrBuilderList() {
    return purchasedItems_;
  }
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
   */
  public int getPurchasedItemsCount() {
    return purchasedItems_.size();
  }
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
   */
  public grpc.services.checkout.CheckoutItem getPurchasedItems(int index) {
    return purchasedItems_.get(index);
  }
  /**
   * <pre>
   * List of the purchased items 
   * </pre>
   *
   * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
   */
  public grpc.services.checkout.CheckoutItemOrBuilder getPurchasedItemsOrBuilder(
      int index) {
    return purchasedItems_.get(index);
  }

  public static final int MESSAGE_FIELD_NUMBER = 4;
  private volatile java.lang.Object message_;
  /**
   * <pre>
   * Result message
   * </pre>
   *
   * <code>string message = 4;</code>
   */
  public java.lang.String getMessage() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      message_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * Result message
   * </pre>
   *
   * <code>string message = 4;</code>
   */
  public com.google.protobuf.ByteString
      getMessageBytes() {
    java.lang.Object ref = message_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      message_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int SUCCESS_FIELD_NUMBER = 5;
  private boolean success_;
  /**
   * <pre>
   * Success flag
   * </pre>
   *
   * <code>bool success = 5;</code>
   */
  public boolean getSuccess() {
    return success_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTransactionIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, transactionId_);
    }
    if (total_ != 0F) {
      output.writeFloat(2, total_);
    }
    for (int i = 0; i < purchasedItems_.size(); i++) {
      output.writeMessage(3, purchasedItems_.get(i));
    }
    if (!getMessageBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, message_);
    }
    if (success_ != false) {
      output.writeBool(5, success_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTransactionIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, transactionId_);
    }
    if (total_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(2, total_);
    }
    for (int i = 0; i < purchasedItems_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, purchasedItems_.get(i));
    }
    if (!getMessageBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, message_);
    }
    if (success_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(5, success_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.checkout.Receipt)) {
      return super.equals(obj);
    }
    grpc.services.checkout.Receipt other = (grpc.services.checkout.Receipt) obj;

    boolean result = true;
    result = result && getTransactionId()
        .equals(other.getTransactionId());
    result = result && (
        java.lang.Float.floatToIntBits(getTotal())
        == java.lang.Float.floatToIntBits(
            other.getTotal()));
    result = result && getPurchasedItemsList()
        .equals(other.getPurchasedItemsList());
    result = result && getMessage()
        .equals(other.getMessage());
    result = result && (getSuccess()
        == other.getSuccess());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TRANSACTION_ID_FIELD_NUMBER;
    hash = (53 * hash) + getTransactionId().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTotal());
    if (getPurchasedItemsCount() > 0) {
      hash = (37 * hash) + PURCHASED_ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getPurchasedItemsList().hashCode();
    }
    hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
    hash = (53 * hash) + getMessage().hashCode();
    hash = (37 * hash) + SUCCESS_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
        getSuccess());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.checkout.Receipt parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.Receipt parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.checkout.Receipt parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.checkout.Receipt parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.Receipt parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.checkout.Receipt parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.checkout.Receipt prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code checkout.Receipt}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:checkout.Receipt)
      grpc.services.checkout.ReceiptOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_Receipt_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_Receipt_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.checkout.Receipt.class, grpc.services.checkout.Receipt.Builder.class);
    }

    // Construct using grpc.services.checkout.Receipt.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPurchasedItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      transactionId_ = "";

      total_ = 0F;

      if (purchasedItemsBuilder_ == null) {
        purchasedItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
      } else {
        purchasedItemsBuilder_.clear();
      }
      message_ = "";

      success_ = false;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.checkout.CheckoutServiceImpl.internal_static_checkout_Receipt_descriptor;
    }

    @java.lang.Override
    public grpc.services.checkout.Receipt getDefaultInstanceForType() {
      return grpc.services.checkout.Receipt.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.checkout.Receipt build() {
      grpc.services.checkout.Receipt result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.checkout.Receipt buildPartial() {
      grpc.services.checkout.Receipt result = new grpc.services.checkout.Receipt(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      result.transactionId_ = transactionId_;
      result.total_ = total_;
      if (purchasedItemsBuilder_ == null) {
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          purchasedItems_ = java.util.Collections.unmodifiableList(purchasedItems_);
          bitField0_ = (bitField0_ & ~0x00000004);
        }
        result.purchasedItems_ = purchasedItems_;
      } else {
        result.purchasedItems_ = purchasedItemsBuilder_.build();
      }
      result.message_ = message_;
      result.success_ = success_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.checkout.Receipt) {
        return mergeFrom((grpc.services.checkout.Receipt)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.checkout.Receipt other) {
      if (other == grpc.services.checkout.Receipt.getDefaultInstance()) return this;
      if (!other.getTransactionId().isEmpty()) {
        transactionId_ = other.transactionId_;
        onChanged();
      }
      if (other.getTotal() != 0F) {
        setTotal(other.getTotal());
      }
      if (purchasedItemsBuilder_ == null) {
        if (!other.purchasedItems_.isEmpty()) {
          if (purchasedItems_.isEmpty()) {
            purchasedItems_ = other.purchasedItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
          } else {
            ensurePurchasedItemsIsMutable();
            purchasedItems_.addAll(other.purchasedItems_);
          }
          onChanged();
        }
      } else {
        if (!other.purchasedItems_.isEmpty()) {
          if (purchasedItemsBuilder_.isEmpty()) {
            purchasedItemsBuilder_.dispose();
            purchasedItemsBuilder_ = null;
            purchasedItems_ = other.purchasedItems_;
            bitField0_ = (bitField0_ & ~0x00000004);
            purchasedItemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPurchasedItemsFieldBuilder() : null;
          } else {
            purchasedItemsBuilder_.addAllMessages(other.purchasedItems_);
          }
        }
      }
      if (!other.getMessage().isEmpty()) {
        message_ = other.message_;
        onChanged();
      }
      if (other.getSuccess() != false) {
        setSuccess(other.getSuccess());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.checkout.Receipt parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.checkout.Receipt) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.lang.Object transactionId_ = "";
    /**
     * <pre>
     * ID of the transaction
     * </pre>
     *
     * <code>string transaction_id = 1;</code>
     */
    public java.lang.String getTransactionId() {
      java.lang.Object ref = transactionId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        transactionId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the transaction
     * </pre>
     *
     * <code>string transaction_id = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTransactionIdBytes() {
      java.lang.Object ref = transactionId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        transactionId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the transaction
     * </pre>
     *
     * <code>string transaction_id = 1;</code>
     */
    public Builder setTransactionId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      transactionId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the transaction
     * </pre>
     *
     * <code>string transaction_id = 1;</code>
     */
    public Builder clearTransactionId() {
      
      transactionId_ = getDefaultInstance().getTransactionId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the transaction
     * </pre>
     *
     * <code>string transaction_id = 1;</code>
     */
    public Builder setTransactionIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      transactionId_ = value;
      onChanged();
      return this;
    }

    private float total_ ;
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 2;</code>
     */
    public float getTotal() {
      return total_;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 2;</code>
     */
    public Builder setTotal(float value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 2;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0F;
      onChanged();
      return this;
    }

    private java.util.List<grpc.services.checkout.CheckoutItem> purchasedItems_ =
      java.util.Collections.emptyList();
    private void ensurePurchasedItemsIsMutable() {
      if (!((bitField0_ & 0x00000004) == 0x00000004)) {
        purchasedItems_ = new java.util.ArrayList<grpc.services.checkout.CheckoutItem>(purchasedItems_);
        bitField0_ |= 0x00000004;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder> purchasedItemsBuilder_;

    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public java.util.List<grpc.services.checkout.CheckoutItem> getPurchasedItemsList() {
      if (purchasedItemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(purchasedItems_);
      } else {
        return purchasedItemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public int getPurchasedItemsCount() {
      if (purchasedItemsBuilder_ == null) {
        return purchasedItems_.size();
      } else {
        return purchasedItemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public grpc.services.checkout.CheckoutItem getPurchasedItems(int index) {
      if (purchasedItemsBuilder_ == null) {
        return purchasedItems_.get(index);
      } else {
        return purchasedItemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder setPurchasedItems(
        int index, grpc.services.checkout.CheckoutItem value) {
      if (purchasedItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePurchasedItemsIsMutable();
        purchasedItems_.set(index, value);
        onChanged();
      } else {
        purchasedItemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder setPurchasedItems(
        int index, grpc.services.checkout.CheckoutItem.Builder builderForValue) {
      if (purchasedItemsBuilder_ == null) {
        ensurePurchasedItemsIsMutable();
        purchasedItems_.set(index, builderForValue.build());
        onChanged();
      } else {
        purchasedItemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder addPurchasedItems(grpc.services.checkout.CheckoutItem value) {
      if (purchasedItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePurchasedItemsIsMutable();
        purchasedItems_.add(value);
        onChanged();
      } else {
        purchasedItemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder addPurchasedItems(
        int index, grpc.services.checkout.CheckoutItem value) {
      if (purchasedItemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePurchasedItemsIsMutable();
        purchasedItems_.add(index, value);
        onChanged();
      } else {
        purchasedItemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder addPurchasedItems(
        grpc.services.checkout.CheckoutItem.Builder builderForValue) {
      if (purchasedItemsBuilder_ == null) {
        ensurePurchasedItemsIsMutable();
        purchasedItems_.add(builderForValue.build());
        onChanged();
      } else {
        purchasedItemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder addPurchasedItems(
        int index, grpc.services.checkout.CheckoutItem.Builder builderForValue) {
      if (purchasedItemsBuilder_ == null) {
        ensurePurchasedItemsIsMutable();
        purchasedItems_.add(index, builderForValue.build());
        onChanged();
      } else {
        purchasedItemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder addAllPurchasedItems(
        java.lang.Iterable<? extends grpc.services.checkout.CheckoutItem> values) {
      if (purchasedItemsBuilder_ == null) {
        ensurePurchasedItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, purchasedItems_);
        onChanged();
      } else {
        purchasedItemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder clearPurchasedItems() {
      if (purchasedItemsBuilder_ == null) {
        purchasedItems_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
      } else {
        purchasedItemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public Builder removePurchasedItems(int index) {
      if (purchasedItemsBuilder_ == null) {
        ensurePurchasedItemsIsMutable();
        purchasedItems_.remove(index);
        onChanged();
      } else {
        purchasedItemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public grpc.services.checkout.CheckoutItem.Builder getPurchasedItemsBuilder(
        int index) {
      return getPurchasedItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public grpc.services.checkout.CheckoutItemOrBuilder getPurchasedItemsOrBuilder(
        int index) {
      if (purchasedItemsBuilder_ == null) {
        return purchasedItems_.get(index);  } else {
        return purchasedItemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public java.util.List<? extends grpc.services.checkout.CheckoutItemOrBuilder> 
         getPurchasedItemsOrBuilderList() {
      if (purchasedItemsBuilder_ != null) {
        return purchasedItemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(purchasedItems_);
      }
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public grpc.services.checkout.CheckoutItem.Builder addPurchasedItemsBuilder() {
      return getPurchasedItemsFieldBuilder().addBuilder(
          grpc.services.checkout.CheckoutItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public grpc.services.checkout.CheckoutItem.Builder addPurchasedItemsBuilder(
        int index) {
      return getPurchasedItemsFieldBuilder().addBuilder(
          index, grpc.services.checkout.CheckoutItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of the purchased items 
     * </pre>
     *
     * <code>repeated .checkout.CheckoutItem purchased_items = 3;</code>
     */
    public java.util.List<grpc.services.checkout.CheckoutItem.Builder> 
         getPurchasedItemsBuilderList() {
      return getPurchasedItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder> 
        getPurchasedItemsFieldBuilder() {
      if (purchasedItemsBuilder_ == null) {
        purchasedItemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.services.checkout.CheckoutItem, grpc.services.checkout.CheckoutItem.Builder, grpc.services.checkout.CheckoutItemOrBuilder>(
                purchasedItems_,
                ((bitField0_ & 0x00000004) == 0x00000004),
                getParentForChildren(),
                isClean());
        purchasedItems_ = null;
      }
      return purchasedItemsBuilder_;
    }

    private java.lang.Object message_ = "";
    /**
     * <pre>
     * Result message
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * Result message
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * Result message
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public Builder setMessage(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      message_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Result message
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public Builder clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Result message
     * </pre>
     *
     * <code>string message = 4;</code>
     */
    public Builder setMessageBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      message_ = value;
      onChanged();
      return this;
    }

    private boolean success_ ;
    /**
     * <pre>
     * Success flag
     * </pre>
     *
     * <code>bool success = 5;</code>
     */
    public boolean getSuccess() {
      return success_;
    }
    /**
     * <pre>
     * Success flag
     * </pre>
     *
     * <code>bool success = 5;</code>
     */
    public Builder setSuccess(boolean value) {
      
      success_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Success flag
     * </pre>
     *
     * <code>bool success = 5;</code>
     */
    public Builder clearSuccess() {
      
      success_ = false;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:checkout.Receipt)
  }

  // @@protoc_insertion_point(class_scope:checkout.Receipt)
  private static final grpc.services.checkout.Receipt DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.checkout.Receipt();
  }

  public static grpc.services.checkout.Receipt getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Receipt>
      PARSER = new com.google.protobuf.AbstractParser<Receipt>() {
    @java.lang.Override
    public Receipt parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Receipt(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Receipt> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Receipt> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.checkout.Receipt getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

