// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: checkout.proto

package grpc.services.checkout;

public interface VoucherResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:checkout.VoucherResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the cart 
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  java.lang.String getCartId();
  /**
   * <pre>
   * ID of the cart 
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCartIdBytes();

  /**
   * <pre>
   * Voucher discount amount
   * </pre>
   *
   * <code>float discount_amount = 2;</code>
   */
  float getDiscountAmount();

  /**
   * <pre>
   * Voucher apply result message
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Voucher apply result message
   * </pre>
   *
   * <code>string message = 3;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Success flag
   * </pre>
   *
   * <code>bool success = 4;</code>
   */
  boolean getSuccess();
}
