// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartcart.proto

package grpc.services.smartcart;

/**
 * <pre>
 * The response message containing the list of items and total price in the cart.
 * </pre>
 *
 * Protobuf type {@code smartcart.CartContents}
 */
public  final class CartContents extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:smartcart.CartContents)
    CartContentsOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CartContents.newBuilder() to construct.
  private CartContents(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CartContents() {
    items_ = java.util.Collections.emptyList();
    cartId_ = "";
    total_ = 0F;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CartContents(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              items_ = new java.util.ArrayList<grpc.services.smartcart.CartItem>();
              mutable_bitField0_ |= 0x00000001;
            }
            items_.add(
                input.readMessage(grpc.services.smartcart.CartItem.parser(), extensionRegistry));
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            cartId_ = s;
            break;
          }
          case 29: {

            total_ = input.readFloat();
            break;
          }
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = java.util.Collections.unmodifiableList(items_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return grpc.services.smartcart.SmartCartServiceImpl.internal_static_smartcart_CartContents_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return grpc.services.smartcart.SmartCartServiceImpl.internal_static_smartcart_CartContents_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            grpc.services.smartcart.CartContents.class, grpc.services.smartcart.CartContents.Builder.class);
  }

  private int bitField0_;
  public static final int ITEMS_FIELD_NUMBER = 1;
  private java.util.List<grpc.services.smartcart.CartItem> items_;
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .smartcart.CartItem items = 1;</code>
   */
  public java.util.List<grpc.services.smartcart.CartItem> getItemsList() {
    return items_;
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .smartcart.CartItem items = 1;</code>
   */
  public java.util.List<? extends grpc.services.smartcart.CartItemOrBuilder> 
      getItemsOrBuilderList() {
    return items_;
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .smartcart.CartItem items = 1;</code>
   */
  public int getItemsCount() {
    return items_.size();
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .smartcart.CartItem items = 1;</code>
   */
  public grpc.services.smartcart.CartItem getItems(int index) {
    return items_.get(index);
  }
  /**
   * <pre>
   * List of items in the cart
   * </pre>
   *
   * <code>repeated .smartcart.CartItem items = 1;</code>
   */
  public grpc.services.smartcart.CartItemOrBuilder getItemsOrBuilder(
      int index) {
    return items_.get(index);
  }

  public static final int CART_ID_FIELD_NUMBER = 2;
  private volatile java.lang.Object cartId_;
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  public java.lang.String getCartId() {
    java.lang.Object ref = cartId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      cartId_ = s;
      return s;
    }
  }
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 2;</code>
   */
  public com.google.protobuf.ByteString
      getCartIdBytes() {
    java.lang.Object ref = cartId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      cartId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TOTAL_FIELD_NUMBER = 3;
  private float total_;
  /**
   * <pre>
   * Total price of all items in the cart
   * </pre>
   *
   * <code>float total = 3;</code>
   */
  public float getTotal() {
    return total_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < items_.size(); i++) {
      output.writeMessage(1, items_.get(i));
    }
    if (!getCartIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, cartId_);
    }
    if (total_ != 0F) {
      output.writeFloat(3, total_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < items_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, items_.get(i));
    }
    if (!getCartIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, cartId_);
    }
    if (total_ != 0F) {
      size += com.google.protobuf.CodedOutputStream
        .computeFloatSize(3, total_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof grpc.services.smartcart.CartContents)) {
      return super.equals(obj);
    }
    grpc.services.smartcart.CartContents other = (grpc.services.smartcart.CartContents) obj;

    boolean result = true;
    result = result && getItemsList()
        .equals(other.getItemsList());
    result = result && getCartId()
        .equals(other.getCartId());
    result = result && (
        java.lang.Float.floatToIntBits(getTotal())
        == java.lang.Float.floatToIntBits(
            other.getTotal()));
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getItemsCount() > 0) {
      hash = (37 * hash) + ITEMS_FIELD_NUMBER;
      hash = (53 * hash) + getItemsList().hashCode();
    }
    hash = (37 * hash) + CART_ID_FIELD_NUMBER;
    hash = (53 * hash) + getCartId().hashCode();
    hash = (37 * hash) + TOTAL_FIELD_NUMBER;
    hash = (53 * hash) + java.lang.Float.floatToIntBits(
        getTotal());
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static grpc.services.smartcart.CartContents parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.smartcart.CartContents parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static grpc.services.smartcart.CartContents parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.smartcart.CartContents parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static grpc.services.smartcart.CartContents parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static grpc.services.smartcart.CartContents parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(grpc.services.smartcart.CartContents prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * The response message containing the list of items and total price in the cart.
   * </pre>
   *
   * Protobuf type {@code smartcart.CartContents}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:smartcart.CartContents)
      grpc.services.smartcart.CartContentsOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return grpc.services.smartcart.SmartCartServiceImpl.internal_static_smartcart_CartContents_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return grpc.services.smartcart.SmartCartServiceImpl.internal_static_smartcart_CartContents_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              grpc.services.smartcart.CartContents.class, grpc.services.smartcart.CartContents.Builder.class);
    }

    // Construct using grpc.services.smartcart.CartContents.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getItemsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        itemsBuilder_.clear();
      }
      cartId_ = "";

      total_ = 0F;

      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return grpc.services.smartcart.SmartCartServiceImpl.internal_static_smartcart_CartContents_descriptor;
    }

    @java.lang.Override
    public grpc.services.smartcart.CartContents getDefaultInstanceForType() {
      return grpc.services.smartcart.CartContents.getDefaultInstance();
    }

    @java.lang.Override
    public grpc.services.smartcart.CartContents build() {
      grpc.services.smartcart.CartContents result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public grpc.services.smartcart.CartContents buildPartial() {
      grpc.services.smartcart.CartContents result = new grpc.services.smartcart.CartContents(this);
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (itemsBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          items_ = java.util.Collections.unmodifiableList(items_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.items_ = items_;
      } else {
        result.items_ = itemsBuilder_.build();
      }
      result.cartId_ = cartId_;
      result.total_ = total_;
      result.bitField0_ = to_bitField0_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return (Builder) super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof grpc.services.smartcart.CartContents) {
        return mergeFrom((grpc.services.smartcart.CartContents)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(grpc.services.smartcart.CartContents other) {
      if (other == grpc.services.smartcart.CartContents.getDefaultInstance()) return this;
      if (itemsBuilder_ == null) {
        if (!other.items_.isEmpty()) {
          if (items_.isEmpty()) {
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureItemsIsMutable();
            items_.addAll(other.items_);
          }
          onChanged();
        }
      } else {
        if (!other.items_.isEmpty()) {
          if (itemsBuilder_.isEmpty()) {
            itemsBuilder_.dispose();
            itemsBuilder_ = null;
            items_ = other.items_;
            bitField0_ = (bitField0_ & ~0x00000001);
            itemsBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getItemsFieldBuilder() : null;
          } else {
            itemsBuilder_.addAllMessages(other.items_);
          }
        }
      }
      if (!other.getCartId().isEmpty()) {
        cartId_ = other.cartId_;
        onChanged();
      }
      if (other.getTotal() != 0F) {
        setTotal(other.getTotal());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      grpc.services.smartcart.CartContents parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (grpc.services.smartcart.CartContents) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<grpc.services.smartcart.CartItem> items_ =
      java.util.Collections.emptyList();
    private void ensureItemsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        items_ = new java.util.ArrayList<grpc.services.smartcart.CartItem>(items_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.smartcart.CartItem, grpc.services.smartcart.CartItem.Builder, grpc.services.smartcart.CartItemOrBuilder> itemsBuilder_;

    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public java.util.List<grpc.services.smartcart.CartItem> getItemsList() {
      if (itemsBuilder_ == null) {
        return java.util.Collections.unmodifiableList(items_);
      } else {
        return itemsBuilder_.getMessageList();
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public int getItemsCount() {
      if (itemsBuilder_ == null) {
        return items_.size();
      } else {
        return itemsBuilder_.getCount();
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public grpc.services.smartcart.CartItem getItems(int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);
      } else {
        return itemsBuilder_.getMessage(index);
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder setItems(
        int index, grpc.services.smartcart.CartItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.set(index, value);
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder setItems(
        int index, grpc.services.smartcart.CartItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.set(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder addItems(grpc.services.smartcart.CartItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder addItems(
        int index, grpc.services.smartcart.CartItem value) {
      if (itemsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureItemsIsMutable();
        items_.add(index, value);
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder addItems(
        grpc.services.smartcart.CartItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder addItems(
        int index, grpc.services.smartcart.CartItem.Builder builderForValue) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.add(index, builderForValue.build());
        onChanged();
      } else {
        itemsBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder addAllItems(
        java.lang.Iterable<? extends grpc.services.smartcart.CartItem> values) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, items_);
        onChanged();
      } else {
        itemsBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder clearItems() {
      if (itemsBuilder_ == null) {
        items_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        itemsBuilder_.clear();
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public Builder removeItems(int index) {
      if (itemsBuilder_ == null) {
        ensureItemsIsMutable();
        items_.remove(index);
        onChanged();
      } else {
        itemsBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public grpc.services.smartcart.CartItem.Builder getItemsBuilder(
        int index) {
      return getItemsFieldBuilder().getBuilder(index);
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public grpc.services.smartcart.CartItemOrBuilder getItemsOrBuilder(
        int index) {
      if (itemsBuilder_ == null) {
        return items_.get(index);  } else {
        return itemsBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public java.util.List<? extends grpc.services.smartcart.CartItemOrBuilder> 
         getItemsOrBuilderList() {
      if (itemsBuilder_ != null) {
        return itemsBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(items_);
      }
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public grpc.services.smartcart.CartItem.Builder addItemsBuilder() {
      return getItemsFieldBuilder().addBuilder(
          grpc.services.smartcart.CartItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public grpc.services.smartcart.CartItem.Builder addItemsBuilder(
        int index) {
      return getItemsFieldBuilder().addBuilder(
          index, grpc.services.smartcart.CartItem.getDefaultInstance());
    }
    /**
     * <pre>
     * List of items in the cart
     * </pre>
     *
     * <code>repeated .smartcart.CartItem items = 1;</code>
     */
    public java.util.List<grpc.services.smartcart.CartItem.Builder> 
         getItemsBuilderList() {
      return getItemsFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        grpc.services.smartcart.CartItem, grpc.services.smartcart.CartItem.Builder, grpc.services.smartcart.CartItemOrBuilder> 
        getItemsFieldBuilder() {
      if (itemsBuilder_ == null) {
        itemsBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            grpc.services.smartcart.CartItem, grpc.services.smartcart.CartItem.Builder, grpc.services.smartcart.CartItemOrBuilder>(
                items_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        items_ = null;
      }
      return itemsBuilder_;
    }

    private java.lang.Object cartId_ = "";
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public java.lang.String getCartId() {
      java.lang.Object ref = cartId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        cartId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public com.google.protobuf.ByteString
        getCartIdBytes() {
      java.lang.Object ref = cartId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        cartId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder setCartId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      cartId_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder clearCartId() {
      
      cartId_ = getDefaultInstance().getCartId();
      onChanged();
      return this;
    }
    /**
     * <pre>
     * ID of the cart
     * </pre>
     *
     * <code>string cart_id = 2;</code>
     */
    public Builder setCartIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      cartId_ = value;
      onChanged();
      return this;
    }

    private float total_ ;
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public float getTotal() {
      return total_;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public Builder setTotal(float value) {
      
      total_ = value;
      onChanged();
      return this;
    }
    /**
     * <pre>
     * Total price of all items in the cart
     * </pre>
     *
     * <code>float total = 3;</code>
     */
    public Builder clearTotal() {
      
      total_ = 0F;
      onChanged();
      return this;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:smartcart.CartContents)
  }

  // @@protoc_insertion_point(class_scope:smartcart.CartContents)
  private static final grpc.services.smartcart.CartContents DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new grpc.services.smartcart.CartContents();
  }

  public static grpc.services.smartcart.CartContents getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CartContents>
      PARSER = new com.google.protobuf.AbstractParser<CartContents>() {
    @java.lang.Override
    public CartContents parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CartContents(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CartContents> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CartContents> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public grpc.services.smartcart.CartContents getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

