// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartcart.proto

package grpc.services.smartcart;

public interface CartStatusOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcart.CartStatus)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * Status message
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <pre>
   * Status message
   * </pre>
   *
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <pre>
   * Success flag
   * </pre>
   *
   * <code>bool success = 2;</code>
   */
  boolean getSuccess();
}
