// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: smartcart.proto

package grpc.services.smartcart;

public interface CartRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:smartcart.CartRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  java.lang.String getCartId();
  /**
   * <pre>
   * ID of the cart
   * </pre>
   *
   * <code>string cart_id = 1;</code>
   */
  com.google.protobuf.ByteString
      getCartIdBytes();
}
